Add a post_update to update the state field of og_membership
jludwig/og pull request #9
Opened 2021-08-04 15:28 UTC by bboro

Noticed there was an entity field definition mismatch error

![image](https://user-images.githubusercontent.com/24897663/128206913-f661db17-6b61-4174-8dff-1a2a20a4e1c8.png)

Pretty much followed [this documentation](https://www.drupal.org/docs/drupal-apis/update-api/updating-entities-and-fields-in-drupal-8#s-updating-a-base-field-type) to add a hook_post_update_NAME(). 

After running the update, the error is gone from status report:

![image](https://user-images.githubusercontent.com/24897663/128208583-09ff5bf1-ecfe-49a0-bab2-8a2f1fe3ee62.png)

The field data looks to be restored successfully. Adding users with different membership states to 2 different groups works successfully after the update.

2021-08-04 15:29 UTC, bboro commented
Hi @MPParsley, re: https://github.com/Gizra/og/pull/231/files#r682629642 ^

2021-08-05 13:06 UTC, bboro commented
cc @amitaibu ^

2021-08-25 13:52 UTC, damienmckenna requested changes

2021-08-25 13:52 UTC, damienmckenna commented on og.install
> +use Drupal\og\OgMembershipInterface;
Can this line be removed?

2021-08-25 13:52 UTC, damienmckenna commented on og.post_update.php
> +  // https://www.drupal.org/docs/drupal-apis/update-api/updating-entities-and-fields-in-drupal-8#s-updating-a-base-field-type
It might work better if the URL was added after the comment with a `@see` line.

2021-08-26 08:43 UTC, MPParsley commented on og.install
> +use Drupal\og\OgMembershipInterface;
```suggestion
```

2021-08-26 08:50 UTC, MPParsley commented
We should probably add a check to see if the schema is correct (e.g. sites that started out with 231.

2021-08-26 08:51 UTC, MPParsley requested changes
Can you add a test to see if the schema is correct before updating it?

2021-08-26 11:08 UTC, bboro commented
Thanks @MPParsley for review. 

Would [`EntityDefinitionUpdateManagerInterface::getChangeList()`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityDefinitionUpdateManagerInterface.php/function/EntityDefinitionUpdateManagerInterface%3A%3AgetChangeList/8.8.x) be the right thing to use here?

2021-09-06 18:09 UTC, MPParsley requested changes

2021-09-06 18:09 UTC, MPParsley commented on og.post_update.php
> +    return t('No entity updates to run.');
We always use TranslatableMarkup instead of t():
```suggestion
    return new TranslatableMarkup('No entity updates to run.');
```

2021-09-06 18:09 UTC, MPParsley commented on og.post_update.php
> +    return t('State field on OG Membership entity is already up to date.');
```suggestion
    return new TranslatableMarkup('State field on OG Membership entity is already up to date.');
```

2021-09-06 18:09 UTC, MPParsley commented on og.post_update.php
> +  return t('State field on OG Membership entity was updated.');
```suggestion
  return new TranslatableMarkup('State field on OG Membership entity was updated.');
```

2021-09-06 18:09 UTC, MPParsley commented on og.post_update.php
> +  // Restore the values back.
```suggestion
  // Restore the values.
```

2021-09-07 13:01 UTC, MPParsley approved these changes

2021-09-07 13:02 UTC, merged